### ISSUE TITLE
[refactoring] 테스트 코드 & 코드 리팩토링

### ISSUE THREAD

**Issue by seong-dodo** [CodeSoom/project-react-4-seong-dodo#181]
### TODO 코드 리팩토링

- [x] DailyTransactonContainer 컴포넌트 리팩토링
- [x] Transacton 컴포넌트 리팩토링
- [x] TransactonData 컴포넌트 리팩토링
- [x] DailyTransacton 컴포넌트 삭제 후 DailyTransactonContainer 컴포넌트 코드 수정

### TODO 테스트 코드 리팩토링

- [x] DailyTransactonModal 테스트 코드 리팩토링
- [x] DailyTransactonContainer 테스트 코드 리팩토링
- [x] Transacton 테스트 코드 리팩토링
- [x] TransactonData 테스트 코드 리팩토링
